[package]
name = "mutxt"
version = "0.1.1"
authors = ["Nathan Moos <moosingin3space@gmail.com>"]

[dependencies]
nix = "0.6"
termion = "1"
bitflags = "0.7"
log = "0.3"
env_logger = "0.3"
clipboard = "0.1"
